var json = {
   "Monday":{
      "Breakfast":{
         "name":"clam chowder",
         "picture_id":"null",
         "calories":"738",
         "ingredients":[
            {
               "name":"sham",
               "quantity":"1.0"
            },
            {
               "name":"chowder",
               "quantity":"0.5"
            },
            {
               "name":"gold",
               "quantity":"0.1"
            }
         ]
      },
      "Lunch":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      },
      "Dinner":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      }
   },
   "Tuesday":{
      "Breakfast":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      },
      "Lunch":{
         "name":"clam chowder",
         "picture_id":"null",
         "calories":"738",
         "ingredients":[
            {
               "name":"sham",
               "quantity":"1.0"
            },
            {
               "name":"chowder",
               "quantity":"0.5"
            },
            {
               "name":"gold",
               "quantity":"0.1"
            }
         ]
      },
      "Dinner":{
         "name":"clam chowder",
         "picture_id":"null",
         "calories":"738",
         "ingredients":[
            {
               "name":"sham",
               "quantity":"1.0"
            },
            {
               "name":"chowder",
               "quantity":"0.5"
            },
            {
               "name":"gold",
               "quantity":"0.1"
            }
         ]
      }
   },
   "Wednesday":{
      "Breakfast":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      },
      "Lunch":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      },
      "Dinner":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      }
   },
   "Thursday":{
      "Breakfast":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      },
      "Lunch":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      },
      "Dinner":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      }
   },
   "Friday":{
      "Breakfast":{
         "name":"clam chowder",
         "picture_id":"null",
         "calories":"738",
         "ingredients":[
            {
               "name":"sham",
               "quantity":"1.0"
            },
            {
               "name":"chowder",
               "quantity":"0.5"
            },
            {
               "name":"gold",
               "quantity":"0.1"
            }
         ]
      },
      "Lunch":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      },
      "Dinner":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      }
   },
   "Saturday":{
      "Breakfast":{
         "name":"clam chowder",
         "picture_id":"null",
         "calories":"738",
         "ingredients":[
            {
               "name":"sham",
               "quantity":"1.0"
            },
            {
               "name":"chowder",
               "quantity":"0.5"
            },
            {
               "name":"gold",
               "quantity":"0.1"
            }
         ]
      },
      "Lunch":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      },
      "Dinner":{
         "name":"clam chowder",
         "picture_id":"null",
         "calories":"738",
         "ingredients":[
            {
               "name":"sham",
               "quantity":"1.0"
            },
            {
               "name":"chowder",
               "quantity":"0.5"
            },
            {
               "name":"gold",
               "quantity":"0.1"
            }
         ]
      }
   },
   "Sunday":{
      "Breakfast":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      },
      "Lunch":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      },
      "Dinner":{
         "name":"ham sandwich",
         "picture_id":"null",
         "calories":"330",
         "ingredients":[
            {
               "name":"bread",
               "quantity":"1.0"
            },
            {
               "name":"ham",
               "quantity":"1.0"
            }
         ]
      }
   }
}